### ISSUE TITLE
[v8] install error --programming error rlation "tms_config_setting" does not exist

### ISSUE THREAD

**Issue by bunhin** [nextma/addons_nextma#3]
Please help, i got the following error during install,  install to a new new database:
 
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 447, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 495, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/opt/odoo/openerp/modules/module.py", line 286, in init_module_models
    result = obj._auto_init(cr, {'module': module_name})
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 2643, in _auto_init
    self._set_default_value_on_column(cr, k, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 2405, in _set_default_value_on_column
    default = default(self, cr, SUPERUSER_ID, context)
  File "/opt/odoo/custom-addons/used-addons/tms/fleet.py", line 501, in <lambda>
    'required_vin': lambda self, cr, uid, ctx: self.pool.get('tms.config.settings')._get_tms_setting_default_values(cr, uid,['required_vin'], ctx),
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom-addons/used-addons/tms/res_config.py", line 72, in _get_tms_setting_default_values
    setting_id = self.search(cr,uid,[(1,'=',1)],limit=1,order='id desc')
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 1650, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4708, in _search
    cr.execute(query_str, where_clause_params)
  File "/opt/odoo/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "tms_config_settings" does not exist
LINE 1: SELECT "tms_config_settings".id FROM "tms_config_settings" W...
                                             ^

**Comment by aitorbouzas** [comment]
Same for me, I hope they can give us an answer. The thing is tms_config_settings is the name of a model inheriting res_config_settings...
